version: 2.1

jobs:
  build-test-and-push:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      # Debugging: Check DockerHub username
      - run:
          name: Check DockerHub Username
          command: echo "DOCKERHUB_USERNAME is $DOCKERHUB_USERNAME"; echo "DOCKERHUB_PASSWORD is $DOCKERHUB_PASSWORD"

      # Authenticate with Docker Hub securely
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Authenticate with Docker Hub
      - setup_remote_docker:
          version: 20.10
      - run:
          name: Log in to Docker Hub
          command: |
            docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Build the Docker image
      - run:
          name: Build the Docker image
          command: docker build -t node-js-sample .

      # Test the running container
      - run:
          name: Test the running container
          command: |
            docker run -d -p 8080:8080 --name app node-js-sample
            sleep 5
            curl -f http://localhost:8080 || (docker logs app && exit 1)

      # Push the Docker image to Docker Hub only if tests pass
      - run:
          name: Push the Docker image
          command: |
            docker tag node-js-sample $DOCKERHUB_USERNAME/node-js-sample:latest
            docker push $DOCKERHUB_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test-and-push
