version: 2.1

jobs:
  build-test-and-push:
    machine: # executor type
      image: ubuntu-2204:current

    steps:
      - checkout

      # Authenticate with Docker Hub
      - setup_remote_docker:
          version: 20.10
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Build the Docker image
      - run:
          name: Build the Docker image
          command: docker build -t node-js-sample .

      # Test the running container
      - run:
          name: Test the running container
          command: |
            docker run -d -p 3000:3000 --name app node-js-sample
            sleep 5
            curl -f http://localhost:3000 || (docker logs app && exit 1)

      # Push the Docker image to Docker Hub only if tests pass
      - run:
          name: Push the Docker image
          command: |
            docker tag node-js-sample $DOCKERHUB_USERNAME/node-js-sample:latest
            docker push $DOCKERHUB_USERNAME/node-js-sample:latest

workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test-and-push
