version: 2.1

orbs:
  docker: circleci/docker@3.1.0

jobs:
    - docker/publish:
        docker-context: .
        image: $DOCKERHUB_USERNAME/node-js-sample:latest
        path: .


# jobs:
#   build-test-and-push:
#     machine: # executor type
#       image: ubuntu-2204:current

#     steps:
#       - checkout

      # - run:
      #     name: Log in to Docker Hub
      #     command: |
      #       echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # - docker/build:
      #   image: "node-js-sample"
      #   tag: "latest"
      #   dockerfile: Dockerfile
      #   context: .

      # Test the container by running it and making sure it's working
      # - run:
      #     name: Test the app
      #     command: |
      #       docker run -d -p 8080:8080 --name app node-js-sample
      #       sleep 5
      #       curl -f http://localhost:8080 || (docker logs app && exit 1)

      # Push the image to Docker Hub
      - docker/push:
          image: "$DOCKERHUB_USERNAME/node-js-sample"
          tag: "latest"

      # # Build the Docker image
      # - run:
      #     name: Build the Docker image
      #     command: docker build -t node-js-sample .

      # Test the running container
      # - run:
      #     name: Test the running container
      #     command: |
      #       docker run -d -p 3000:8080 --name app node-js-sample
      #       sleep 5
      #       curl -f http://localhost:3000 || (docker logs app && exit 1)

      # # Push the Docker image to Docker Hub only if tests pass
      # - run:
      #     name: Push the Docker image
      #     command: |
      #       docker tag node-js-sample $DOCKERHUB_USERNAME/node-js-sample:latest
      #       docker push $DOCKERHUB_USERNAME/node-js-sample:latest

workflows:
  version: 2
  # build-and-push:
  #   jobs:
  #     - build-test-and-push
  build-and-push:
    jobs:
      - build-docker-image-only
